# Generated by Django 4.1.7 on 2023-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('busID', models.IntegerField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=20)),
                ('operator', models.SmallIntegerField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('lastStop', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
